#Version 0.1

services:
  jobs-postgres:
    image: postgres:16
    container_name: jobs_postgres
    environment:
      POSTGRES_USER: ${JOBS_DB_USER}
      POSTGRES_PASSWORD: ${JOBS_DB_PASSWORD}
      POSTGRES_DB: ${JOBS_DB_NAME}
    ports:
      - "${JOBS_DB_HOST_PORT}:5432" #"HOST_PORT:CONTAINER_PORT"
    volumes:
      - jobs_postgres_data:/var/lib/postgresql/data
      - ./db/jobs/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # detections-postgres:
  #   image: postgres:16
  #   container_name: detections_postgres
  #   environment:
  #     POSTGRES_USER: ${DETECTIONS_DB_USER}
  #     POSTGRES_PASSWORD: ${DETECTIONS_DB_PASSWORD}
  #     POSTGRES_DB: ${DETECTIONS_DB_NAME}
  #   ports:
  #     - "${DETECTIONS_DB_HOST_PORT}:5432"
  #   volumes:
  #     - detections_postgres_data:/var/lib/postgresql/data
  #     - ./db/detections/init:/docker-entrypoint-initdb.d:ro
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  # rabbitmq:
  #   image: rabbitmq:3.13-management
  #   container_name: detection_rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${MESSAGE_BROKER_USER}
  #     RABBITMQ_DEFAULT_PASS: ${MESSAGE_BROKER_PASSWORD}
  #   ports:
  #     - "${RABBITMQ_HOST_PORT}:5672"
  #     - "${RABBITMQ_UI_HOST_PORT}:15672"
  #   volumes:
  #     - detection_rabbitmq_data:/var/lib/rabbitmq
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
    

  # api-service:
  #   build:
  #     context: . # какая папка будет видна Dokerfile для сборки 
  #     dockerfile: services/detection-job-service/Dockerfile # путь к dokerfile относительно context
  #   container_name: detection_api
  #   environment:
  #     RABBITMQ_HOST: ${RABBITMQ_HOST}
  #     RABBITMQ_PORT: ${RABBITMQ_PORT}
  #     RABBITMQ_USER: ${MESSAGE_BROKER_USER}
  #     RABBITMQ_PASSWORD: ${MESSAGE_BROKER_PASSWORD}
      
  #     JOBS_DB_HOST: ${JOBS_DB_HOST}
  #     JOBS_DB_PORT: ${JOBS_DB_PORT}
  #     JOBS_DB_USER: ${JOBS_DB_USER}
  #     JOBS_DB_PASSWORD: ${JOBS_DB_PASSWORD}
  #     JOBS_DB_NAME: ${JOBS_DB_NAME}

  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   ports:
  #     - "${API_HOST_PORT}:8080"

  # detection-worker:
  #   build:
  #     context: .
  #     dockerfile: services/detection-worker/Dockerfile
  #   container_name: detection_worker
  #   environment:
  #     RABBITMQ_HOST: ${RABBITMQ_HOST}
  #     RABBITMQ_PORT: ${RABBITMQ_PORT}
  #     RABBITMQ_USER: ${MESSAGE_BROKER_USER}
  #     RABBITMQ_PASSWORD: ${MESSAGE_BROKER_PASSWORD}

  #     JOBS_DB_HOST: ${JOBS_DB_HOST}
  #     JOBS_DB_PORT: ${JOBS_DB_PORT}
  #     JOBS_DB_USER: ${JOBS_DB_USER}
  #     JOBS_DB_PASSWORD: ${JOBS_DB_PASSWORD}
  #     JOBS_DB_NAME: ${JOBS_DB_NAME}

  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   ports:
  #     - "${DETECTION_WORKER_PORT}:8081"


volumes:
  jobs_postgres_data:
  # detections_postgres_data:
  # detection_rabbitmq_data: